checkout the previously less broken version of this

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,42 +1,40 @@
 #!/usr/bin/env bash
-## bin/detect <build-dir>
-#
+# bin/detect <build-dir>
+
 echo 'aiven-deploy-detect'
-#
+
 BUILD_DIR=$1
-#
+
 echo $(ls -la .)
-#
-############ app.json requirements
-##  "buildpacks": [
-##    {
-##      "url": "https://github.com/heroku/heroku-buildpack-cli"
-##    },
-##    {
-##      "url": "https://github.com/heroku/heroku-buildpack-python"
-##    },
-##   ],
-############
-#
-##if ! [ -x "$(command -v python)" ]; then
-##  echo 'Error: python is not installed.' >&2
-##  exit 1
-##else
-##  echo 'python version:'
-##  echo     "$(python --version)"
-##fi
-##
-##if [ -n "${HEROKU_BIN}" ]; then
-##  if [ -f "$BUILD_DIR/.profile.d/heroku-cli.sh" ]; then
-##      source "$BUILD_DIR/.profile.d/heroku-cli.sh"
-##  else
-##      echo "heroku buildpack not installed in app.json buildpacks: https://github.com/heroku/heroku-buildpack-cli" >&2
-##      exit 1
-##  fi
-##fi
-##
-### hmmm, not sure why python 3.8.10 is available here ....
-### python -c "import pip"
-### python -c "import invoke"
-##
-##exit 0
+
+########### app.json requirements
+#  "buildpacks": [
+#    {
+#      "url": "https://github.com/heroku/heroku-buildpack-cli"
+#    },
+#    {
+#      "url": "https://github.com/heroku/heroku-buildpack-python"
+#    },
+#   ],
+###########
+
+if ! [ -x "$(command -v python)" ]; then
+  echo 'Error: python is not installed.' >&2
+  exit 1
+else
+  echo 'python version:'
+  echo     "$(python --version)"
+fi
+
+if [ -f "$BUILD_DIR/.profile.d/heroku-cli.sh" ]; then
+    source "$BUILD_DIR/.profile.d/heroku-cli.sh"
+else
+    echo "heroku buildpack not installed in app.json buildpacks: https://github.com/heroku/heroku-buildpack-cli" >&2
+    exit 1
+fi
+
+
+python -c "import pip"
+python -c "import invoke"
+
+exit 0
