fail if heroku buildpack not installed

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -5,13 +5,32 @@ echo 'aiven-deploy-detect'
 
 echo $(ls -la .)
 
+########### app.json requirements
+#  "buildpacks": [
+#    {
+#      "url": "https://github.com/heroku/heroku-buildpack-cli"
+#    },
+#    {
+#      "url": "https://github.com/heroku/heroku-buildpack-python"
+#    },
+#   ],
+###########
+
+if ! [ -x "$(command -v heroku)" ]; then
+  echo 'Error: heroku is not installed.' >&2
+  exit 1
+else
+  echo 'heroku version:'
+  echo     "$(pip --version)"
+fi
+
 
 if ! [ -x "$(command -v python)" ]; then
   echo 'Error: python is not installed.' >&2
   exit 1
 else
   echo 'python version:'
-  echo     "$(pip --version)"
+  echo     "$(python --version)"
 fi
 
 python -c "import pip"
